/*
 * CRUD API iex
 * CRUD API client for iex data platform
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {CreateApi} from './api/CreateApi';
import {DatasetDataOperationApi} from './api/DatasetDataOperationApi';
import {DatasetOperationApi} from './api/DatasetOperationApi';
import {DeleteApi} from './api/DeleteApi';
import {DeleteDatasetDataApi} from './api/DeleteDatasetDataApi';
import {ModifyApi} from './api/ModifyApi';

/**
* CRUD_API_client_for_iex_data_platform.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CrudApiIex = require('index'); // See note below*.
* var xxxSvc = new CrudApiIex.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CrudApiIex.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CrudApiIex.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CrudApiIex.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
    * The CreateApi service constructor.
    * @property {module:api/CreateApi}
    */
    CreateApi,

    /**
    * The DatasetDataOperationApi service constructor.
    * @property {module:api/DatasetDataOperationApi}
    */
    DatasetDataOperationApi,

    /**
    * The DatasetOperationApi service constructor.
    * @property {module:api/DatasetOperationApi}
    */
    DatasetOperationApi,

    /**
    * The DeleteApi service constructor.
    * @property {module:api/DeleteApi}
    */
    DeleteApi,

    /**
    * The DeleteDatasetDataApi service constructor.
    * @property {module:api/DeleteDatasetDataApi}
    */
    DeleteDatasetDataApi,

    /**
    * The ModifyApi service constructor.
    * @property {module:api/ModifyApi}
    */
    ModifyApi
};
