/*
 * CRUD API iex
 * CRUD API client for iex data platform
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";

/**
* Create service.
* @module api/CreateApi
* @version 1.0.1
*/
export class CreateApi {

    /**
    * Constructs a new CreateApi. 
    * @alias module:api/CreateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the datasetsProviderIdPost operation.
     * @callback moduleapi/CreateApi~datasetsProviderIdPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} provider data provider name
     * @param {String} id dataset id
     * @param {String} token pk or sk token
     * @param {Object} opts Optional parameters
     * @param {Number} opts.maximumValidationErrors allowed maximum validation errors
     * @param {module:api/CreateApi~datasetsProviderIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    datasetsProviderIdPost(provider, id, token, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'provider' is set
      if (provider === undefined || provider === null) {
        throw new Error("Missing the required parameter 'provider' when calling datasetsProviderIdPost");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling datasetsProviderIdPost");
      }
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling datasetsProviderIdPost");
      }

      let pathParams = {
        'provider': provider,'id': id
      };
      let queryParams = {
        'token': token,'maximumValidationErrors': opts['maximumValidationErrors']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json', 'application/x-jsonl', 'text/csv'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/datasets/{provider}/{id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the datasetsProviderPost operation.
     * @callback moduleapi/CreateApi~datasetsProviderPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} provider data provider name
     * @param {String} token pk or sk token
     * @param {Object} opts Optional parameters
     * @param {Number} opts.maximumValidationErrors allowed maximum validation errors
     * @param {module:api/CreateApi~datasetsProviderPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    datasetsProviderPost(provider, token, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'provider' is set
      if (provider === undefined || provider === null) {
        throw new Error("Missing the required parameter 'provider' when calling datasetsProviderPost");
      }
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling datasetsProviderPost");
      }

      let pathParams = {
        'provider': provider
      };
      let queryParams = {
        'token': token,'maximumValidationErrors': opts['maximumValidationErrors']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json', 'application/x-jsonl', 'text/csv'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/datasets/{provider}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}